### ISSUE TITLE
Review vp-toolkit

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/interoperability#28]
https://github.com/rabobank-blockchain/vp-toolkit#flow

**Comment by rabomarnix** [comment]
Hi,

Thank you for taking the time to review our [SSI flow](https://github.com/rabobank-blockchain/vp-toolkit#flow).

## Background
A while back we saw various identity protocols popping up. In a few PoC's we needed to use different protocols - so instead of hardcoding the protocol in the mobile wallet, we decided to make a flexible plugin system which allows developers to plug in the protocols they would like to support. This framework is called [Universal Ledger Agent](https://github.com/rabobank-blockchain/universal-ledger-agent) - but it's basically a small message bus, broadcasting message inside the application during runtime. [More background info on our SSI journey here](https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/topics-and-advance-readings/universal-ledger-agent.md) and a [video here](https://youtu.be/ZV52KpE_yaU).

## Plugins
We published ULA plugins for the mobile wallet conform the SSI flow as mentioned above, along with some standalone libraries to perform generic tasks. [This is a list of libraries and plugins](https://github.com/rabobank-blockchain/universal-ledger-agent/blob/develop/docs/Integration.md#understanding-the-components). We are going to test the integration with new [Hyperledger Aries plugins](https://github.com/ula-aca) soon, so both identity protocols are supported in one app.

## Flow
The issuer shows a QR code containing an endpoint. This endpoint resolves to a ChallengeRequest object, simply stating what the issuer wants to do: Issue x amount of data points. The holder app then creates x amount of private keys (or derives them) and calculates the Ethereum addresses - one for each data point, and sends a map of *predicate -> address* back to the issuer. The issuer then includes the address in the right VC. Then the issuer sumbits an Ethereum transaction for each address into the VcStatusRegistry smart contract. The issuer can revoke the validity of the data by removing the predicate address from the smart contract.

The verifier checks the cryptography and the smart contract if the entry is still there.

## Drawbacks
- Our DID structure is `did:eth:address` and uses the deprecated `eth` namespace;
- We haven't switched to the `ethr` namespace and our code isn't yet involving a DID resolver. The public key used for VC/VP verification resides in the `proof.verificationMethod` field;
- Each data point becomes a new VerifiableCredential in order to maintain data minimalization. This makes correlation tougher, which makes some use cases (requiring correlation) more difficult. We might switch to a [selective disclosure](https://docs.opencerts.io/appendix_data_obfuscation.html#understanding-the-data-obfuscation-process) strategy using hashes;
- Our protocol has no interaction with data hubs yet.
